name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        # You may pin to the exact commit or the version.
        # uses: Adzz/yarn_command_action@ad5d5595701709c7deecfd9528bd5ed9681d5e8a
        uses: Adzz/yarn_command_action@v2.0.0
        with:
          # Specify whether to use npm or yarn to run the tests. May be npm or yarn only defaults to yarn
          package-manager: npm
          # The command you wish to run e.g. test
          command: test
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd ./transTwitterBot
            git pull
            echo 'Deployment successful to digital ocean' 
            npm install
            npm install pm2 -g
            pm2 restart TTB
